version: "3.8"
services:
  medusa:
    build: ./medusa-backend
    env_file: ./medusa-backend/.env
    ports:
      - "9000:9000"
    restart: unless-stopped

  storefront:
    build: ./pps-sveltekit
    ports:
      - "5173:5173"
    args:
      DATABASE_URL: ${DATABASE_URL}
    environment:
      - DATABASE_URL=file:local.db
    restart: unless-stopped
