version: "3.8"
services:
  medusa:
    build: ./medusa-backend
    # env_file: ./medusa-backend/.env
    ports:
      - "9000:9000"
    restart: unless-stopped

  storefront:
    build:
      context: ./pps-sveltekit
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5173:5173"
    # environment:
    #   PUBLIC_API_URL: "http://localhost:9000"
    restart: unless-stopped
