version: "3.8"
services:
  medusa:
    build: ./medusa-backend
    # env_file: ./medusa-backend/.env
    ports:
      - "9000:9000"
    restart: unless-stopped

  storefront:
    build:
      context: ./pps-sveltekit
      args:
        DATABASE_URL: ${DATABASE_URL:-file:local.db}
    environment:
      - DATABASE_URL=${DATABASE_URL:-file:local.db}
      - PUBLIC_API_URL=http://192.168.4.138:9000
    ports:
      - "5173:5173"
    restart: unless-stopped
