version: "3.8"
services:
  medusa:
    build:
      context: ./medusa-backend
      args:
        MEDUSA_DATABASE_URL: ${MEDUSA_DATABASE_URL}
    # env_file: ./medusa-backend/.env
    environment:
      - MEDUSA_DATABASE_URL=${MEDUSA_DATABASE_URL}
    ports:
      - "9000:9000"
    restart: unless-stopped

  storefront:
    build:
      context: ./pps-sveltekit
      args:
        DATABASE_URL: ${DATABASE_URL:-file:local.dbb}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5173:5173"
    restart: unless-stopped
